apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sqlsrvr
  name: sqlsrvr
spec:
  containers:
  - image: nginx
    name: sqlsrvr
    resources: {}
    envFrom:
    - configMapRef:
        name: db-config
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
